---
title: "Estudio correlacional entre las propiedades físico-químicas y microbiológicas de los suelos de Puchuncaví aledaños a la refinería CODELCO Ventanas"
author: "Natali Zamora Bugueño"
date: "20-10-2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bookdown)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
library(devtools)
library(kableExtra)
library(knitr)
library(FactoMineR)
library(factoextra)
library(readxl)
library(broom)
data <- read_excel("data.xlsx")
```

## Introducción

Chile basa gran parte de su economía en la extracción, refinación y exportación de metales como el cobre y zinc, posicionándose a nivel mundial entre los primeros países con mayor producción, llegando a aportar hasta un 31,5% de demanda mundial de cobre (Comisión Chilena de Cobre <http://www.cochilco.cl>, cuya producción que se genera principalmente entre las regiones norte a centro del país. 
Los problemas ambientales asociados con la minería son ampliamente conocidos, particularmente en relación a la contaminación de suelos con metales, elementos que disminuyen la calidad y presentan riesgo para el buen funcionamiento de este *(Bloem et al. 2009)*.
Gran parte de esta producción se centra en las regiones centrales y sur del país, donde ocurre un solapamiento de los sectores productivos generando contaminación de metales en suelos de carácter agrícola; como lo reporta *Parra et al., 2014*.
Si bien se conoce la respuesta de algunas bacterias a la presión causada por elevadas concentraciones de metales, no existen estudiosque evalúen cómo se comportan aislados ambientales que se encuentran en suelos que ya tienen altas concentraciones de estos elementos.
Es por esto que el presente estudio es del tipo exploratorio con alcance correlacional y descriptivo en donde se caracterizará las características físico-químicas y biológicas medidas en los suelos aledaños a empresas mineras.
Conociendo la problemática que se presenta en los suelos de la región de Valparaíso los cuales tienen registro de actividad minera y refinadora de cobre por los últimos 60 años, nos preguntamos qué ocurre la diversidad bacteriana de los suelos aledaños a las refinerías de cobre y cómo les afecta la presencia de altas concentraciones de metales pesados, lo cual será proyectado a través de un modelo lineal simple o múltiple desarrollado en la investigación.

## Metodología:

 **Área de estudio:** Para el presente estudio, se seleccionaron los sectores de Puchuncaví pertenecientes a la Región de Valparaíso, como áreas de estudio ya que presentan suelos de carácter agrícola históricamente contaminados. Para cada muestra se registraron las coordenadas y el tipo de cultivo presente. En cada punto se tomaron cuatro muestras de igual tamaño las cuales fueron mezcladas y posteriormente tamizadas en una malla de 2 mm para obtener una sola muestra compuesta. Las muestras fueron conservadas a 4°C hasta su uso.  

**Determinación de las características físico-químicas:**Para determinar las características fisicoquímicas generales de los suelos, se recolectó 1 kg desub-muestra la cual fue guardada en bolsas resellables y una alícuota de 50 gr fue guardada en tubo falcon bajo condiciones esteriles para los análisis microbiológicos. Cada sub-muestra fue secada a 40°C por 48 horas. Las características fisicoquímicas generales de los suelos (conductividad eléctrica, pH, contenido de materia orgánica, relación carbono-nitrógeno y texturas) fueron determinadas por métodos de rutina *(Verdejo et al. 2015)*. Las concentraciones de cobre disponible y de metales totales y solubles fueron determinadas por espectroscopia atómica de masas. Los análisis fueron realizados por el Laboratorio de Suelos y Análisis Foliar de la Facultad de Agronomía de la PUCV. 
 
**Determinación del número de bacterias en las muestras de suelo:** Para la determinación del número de bacterias se utilizó el método de número más probable (NMP) *(Cochran, 1950)*. Se pesó 10 g de suelo seco y se diluyeron en 90 ml de buffer fosfato (PBS). La solución fue sometida a agitación orbital a 200 rpm por 30 min a 30°C para homogenizar y disolver los agregados de suelo *(Altimira et al. 2012)*. Mientras que la diversidad fue estimada por 


